apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-ingress
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  dependsOn:
    - name: infra