apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth
  namespace: monitoring
type: Opaque
data:
  # admin:monitoring123 (format htpasswd)
  users: YWRtaW46JDJhJDEwJGVqTFZKRjNod1NHZmFhT1pNYzB4UC5VSmdjSXpPeHE5aGkwQ2dsMUVDV0tpSWphQjhlTTZ5Cg==