apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth
  namespace: monitoring
type: Opaque
data:
  # backlight:QR4xQ7QL5ppPhp (format htpasswd)
  users: YmFja2xpZ2h0OiQyeSQxMCRHc2ZwZWJIM3NEejljcUdGWXBxLk1ldTNLRzZNUDBlTzFaZWpncHlQV1luUkZRcU1Cb1hMTwo=