apiVersion: v1
kind: Service
metadata:
  name: api-enrichment
  namespace: app
  labels:
    app: api-enrichment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: api-enrichment