apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api-gateway
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: api-gateway
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^sha-[a-f0-9]+'
    extract: '$0'