apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: app
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: api-gateway